name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Create .ssh directory
      run: mkdir -p ~/.ssh
      shell: bash

    - name: Add remote server to known hosts
      run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      shell: bash

    - name: Deploy to AWS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > Omni.pem
        chmod 600 Omni.pem
        rsync -avz --delete --exclude '.git' --exclude 'node_modules' --exclude 'Omni.pem' --exclude 'public/' -e "ssh -i Omni.pem" . $USER@$HOST:/var/www/html/Omni
        ssh -i Omni.pem $USER@$HOST "cd /var/www/html/Omni && npm install && pm2 restart all"
      shell: bash